file:
  client-path: "/file"
  storage-location: "D://new/"
  base-uri: http://localhost:${server.port}${file.client-path}/
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  application:
    name: ITE-Gen3-Eco
#    update file size (min -> max)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080